### ISSUE TITLE
Establishing Style Guidelines

### ISSUE THREAD

**Issue by ghost** [Anatolij-Grigorjev/MopedRebel#3]
The code in its current state doesn't follow [the GDScript Style Guide.](https://docs.godotengine.org/en/3.0/getting_started/scripting/gdscript/gdscript_styleguide.html) If we brought it in line stylistically, it will make the game specific code line up with the engine's built-in code more cleanly. Additionally, it would make it easier to keep coding styles consistent with multiple developers. It would also make the code easier to understand for anyone seeing the project for the first time.

Alternatively, if a different set of style guidelines is preferred, it would be best to make that clear somewhere. This could either be done by linking to an outside document or writing something and adding it to the repository.

@Anatolij-Grigorjev if this seems like too much of a pain, no worries. I'll just figure out how to make my code look like yours by following what you've already written. Alternatively, if it's something you'd like to do, I'm happy to go through and make all the conversions and make a PR for it.

**Comment by Anatolij-Grigorjev** [comment]
Ok, thanks for bringing the actual style guide to my attention!

Now that I have had time to look through it I'm glad that most of what I write already aligns with it based on general sane coding and readability sensibilities, as well as my interpretations of the built-in gdscript style.
Obviously some areas arent adhering as meticilously as they probably should and the things written in the guide seem to make sense OK to me, so I have nothing against moving forward with it in mind. 
I wont try adhering to it to the letter or anything, but correcting things like packed scenes to be uppercased like class names or making all signals past tense or adding underscores at start of private vars and methods sure sound pretty good. 
Ill do minor refactorings to this effect on my own through the code as I work on this or that feature/bug, but if you have a solid idea about changing a large chunk without reducing readability I wont mind reading and merging it
